version: '3.7'

services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    # http://localhost:16686
    ports:
      - "5775:5775/udp"    # Agent UDP port
      - "6831:6831/udp"    # Agent UDP port for sending traces
      - "6832:6832/udp"    # Agent UDP port for communication between agents
      - "5778:5778"        # HTTP port for metrics and sampling
      - "16686:16686"      # Jaeger UI
      - "14268:14268"      # Collector HTTP endpoint
      - "14250:14250"      # GRPC endpoint
      - "9411:9411"        # Zipkin-compatible HTTP endpoint
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411 # Enable Zipkin compatibility
      - JAEGER_SAMPLER_TYPE=const # The type of sampler (const, probabilistic, rateLimiting, or remote).
      - JAEGER_SAMPLER_PARAM=1 # 1 for always sampling
